### ISSUE TITLE
Sleep

### ISSUE THREAD

**Issue by juliovalco** [hackintosh-efi/dell-optiplex-3080-mff#1]
hi, sleep doesn't work.. bios config ok, dvmt and cfg-lock ok.. any clue?

thanks

**Comment by mrasong** [comment]
Works well on my side.
can you give a detail info?

**Comment by mrasong** [comment]
BIOS setting like below:
```
PowerManagement
  |-- Block Sleep:        YES
```

**Comment by juliovalco** [comment]
Hi, yes, i disabled Block Sleep and now it's working fine!..thanks a lot!
