### ISSUE TITLE
optiplex 3080 mff either freezes or kernel panic at install boot

### ISSUE THREAD

**Issue by pwky1225** [hackintosh-efi/dell-optiplex-3080-mff#10]
I am using the latest EFI 0.9.9.0311 with the default config.plist which doesn't have any of the WLAN/BT kext in it. I tried it with both Sonoma and Ventura USB boot sticks. With Sonoma, it boots past verifying base.dmg and bunch of screens scroll by and it just freezes. In Ventura, I get past the verify base.dmg and it kernel panics right after.

Here are my specs:

    BIOS: 2.18.0 (Can't downgrade anymore. I started at 2.20.0)
    Chipset: DELL B460
    CPU: Intel 10th i5-10500T
    Memo: SK hynix 8GB(1x8GB) DDR4 2666 Mhz
    iGPU: Intel UHD Graphic 630
    HDA: Realtek ALC3246(ALC256)
    SSD: Hynix 256G  m.2 2230
    LAN: Realtek RTL8186
    WLAN: none
    PSU: DELL 65w

I did the RU.efi and changed both CPUSetup and SaSetup to the proper values. This was when I was still at Bios 2.20.0. After I downgraded to 2.18.0, those values didn't change when I booted with RU.efi. I overwrote them anyways. 

I also set all the Bios settings according to the Readme. Except on my 3080, I do not have a PTT setting. Only a TPM setting. I tried disabling TPM or unchecking TMP2.0, that just causes an immediate kernel panic with Sonoma during install boot. 

I am totally stuck and not sure how to proceed. Any help is appreciated! Thanks.

**Comment by pwky1225** [comment]
Figured it out. It was an incompatible NVME. Got a WD SN580 1TB and all my problems went away.

**Comment by mrasong** [comment]
Not recommended to use Samsung / Hynix SSD.
