### ISSUE TITLE
Keyboard mapping 

### ISSUE THREAD

**Issue by cali0028** [hackintosh-efi/dell-optiplex-3080-mff#2]
Hey there. 

I’ve installed the latest version and seems like your missing the keyboard mapping. 

So every time reboot it will ask me to setup keyboard again

**Comment by mrasong** [comment]
> 

I dont think this is an EFI issue.
Nerver happend to me.

**Comment by mrasong** [comment]
I seems that if you set it once, macOS will not ask you to setup it again when you use THE SAME keyboard.
