### ISSUE TITLE
can anyone share installing instructions?

### ISSUE THREAD

**Issue by Nothabeebi** [hackintosh-efi/dell-optiplex-3080-mff#4]
Need Install instructions please.

**Comment by gatorback** [comment]
https://dortania.github.io/OpenCore-Install-Guide/

**Comment by patrickwasp** [comment]
Here are some notes on installation. Refer to the linked guide above for more details. 

1. download macOS 
 ```
  softwareupdate --list-full-installers;echo;echo "Please enter version number you wish to download:";read;$(if [ -n "$REPLY" ]; then; echo "softwareupdate --fetch-full-installer --full-installer-version "$REPLY; fi);
```
enter 13.6.1

3. plug in USB drive and format it as described in the guide (I named it "ventura")
4. flash the drive
```
sudo /Applications/Install\ macOS\ Ventura.app/Contents/Resources/createinstallmedia --volume /Volumes/ventura
```
5. Mount EFI using ./MountEFI.command
6. Copy the EFI folder from this repo into the EFI partition (including the root EFI folder)
7. download the RU.efi file from this repo
8. rename RU.efi to BOOTx64.efi and move overwrite the original file in the EFI/BOOT folder
9. plug in the drive into your 3080
10. press "ALT" + "=" and search for `CPUSetup` change the value as shown in the screen shot. Repeat for `SaSetup`
11. shutdown and load up the EFI partition to replace the BOOTx64.efi to the original one
12. plug back in and boot into the installer 
13. install macOS (format your internal drive to APFS with GUID)
14. during the installation it will reboot multiple times, it should boot back into the installer on its own
15. follow the guide to replace your internal drive's EFI contents with that of the USB EFI partition
