### ISSUE TITLE
求dell-optiplex-3080-sff EFI配置

### ISSUE THREAD

**Issue by theores** [hackintosh-efi/dell-optiplex-3080-mff#5]
大佬，dell-optiplex-3080 sff版本怎么配置EFI啊？我下载你的这个试了下卡在第一步Logo那里了。
sff版本的配置是：

BIOS: 1.3.10
主板: 戴尔 B460
**处理器: Intel 10代 i3-10100**
内存: 海力士 16GB(2x8GB) DDR4 3200 Mhz
显卡: 英特尔® 超核芯显卡 630
声卡: Realtek ALC3246(ALC256)
硬盘: 铠侠 Kioxia 512G (KBG40ZNS) m.2 2230
网卡: Realtek RTL8111HSD-CG
无线: 无
电源: 戴尔 65W

(只有CPU处理器和BIOS版本不同，其它都一样)

**Comment by WuLongMiTaoLaiYiDa** [comment]
安装方式相同，需要用RU.efi工具解锁CFG LOCK 并修改 DVMT ，DELL BIOS 提取出来的位置同系应该一直，可以参考https://www.bilibili.com/video/BV1LV4y1N7jF/  解锁CFG LOCK的视频
