### ISSUE TITLE
New BIOS version - support?

### ISSUE THREAD

**Issue by discmeister** [hackintosh-efi/dell-optiplex-3080-mff#8]
Hi there,

Picked up a 3080 Micro hoping to use this guide and EFI but it turns out it's been updated to the latest Dell BIOS, which is 2.20.0. Do you know if the ru.efi patches will still work with this BIOS?

Kind regards,

Discy

**Comment by mrasong** [comment]
Not sure for that, just try it.

**Comment by discmeister** [comment]
Hi there. I'm trying it now. The CPU setup screen looked exactly as it does on your guide, so I'm reasonably optimistic about it. The sasetup screen had 01 in the parameter where you say it's normally 00 - but I changed it to 02 as per the guide anyway, and am now trying to boot up the Mac installer. Will report back.

**Comment by discmeister** [comment]
I can confirm that the Ventura install went without a hitch, CFG-lock is disabled and the machine appears to have the full quote of RAM allocated to video. You may want to update your guide to include compatibility with 2.20.0 - with the caveat about it being very slightly different upon first inspection, as outlined above. Many thanks for your guide/EFI - tremendously useful and what a great little machine this is as a Hackintosh.

**Comment by WuLongMiTaoLaiYiDa** [comment]
> I can confirm that the Ventura install went without a hitch, CFG-lock is disabled and the machine appears to have the full quote of RAM allocated to video. You may want to update your guide to include compatibility with 2.20.0 - with the caveat about it being very slightly different upon first inspection, as outlined above. Many thanks for your guide/EFI - tremendously useful and what a great little machine this is as a Hackintosh.

Thank you for testing and providing feedback，Have fun with hackintosh .
